# Generated by Django 2.2.7 on 2019-11-30 01:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('udaic_profile', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='udaicuser',
            name='email',
            field=models.EmailField(max_length=254, null=True),
        ),
    ]
