# Generated by Django 2.2.7 on 2019-11-29 19:07

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('udaic_profile', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BaseSupport',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=200, null=True)),
                ('creation_date', models.DateField(auto_now_add=True)),
                ('slug', models.SlugField(max_length=255, unique=True)),
                ('client_user', models.ManyToManyField(to='udaic_profile.UdaicClient')),
                ('support_user', models.ManyToManyField(to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Asesoramiento Base',
                'verbose_name_plural': 'Asesoramientos Base',
            },
        ),
        migrations.CreateModel(
            name='SupportSession',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('base_support', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='udaic_support_sessions.BaseSupport')),
            ],
        ),
    ]
