# Generated by Django 2.2.7 on 2019-11-29 11:02

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import udaic_support_sessions.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BaseSupport',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=200, null=True)),
                ('creation_date', models.DateField(auto_now_add=True)),
                ('slug', models.SlugField(max_length=255, unique=True)),
            ],
            options={
                'verbose_name': 'asesoramiento base',
                'verbose_name_plural': 'udaic_support_sessions base',
            },
        ),
        migrations.CreateModel(
            name='SupportSession',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('base_support', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='udaic_support_sessions.BaseSupport')),
            ],
        ),
        migrations.CreateModel(
            name='SupportPerson',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=200, null=True)),
                ('last_name', models.CharField(max_length=200, null=True)),
                ('user', models.ForeignKey(on_delete=models.SET(udaic_support_sessions.models.get_sentinel_user), to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'usuario UdAIC',
                'verbose_name_plural': 'usuarios UdAIC',
            },
        ),
    ]
